improvements

diff --git a/.github/workflows/pypi_deploy.yml b/.github/workflows/pypi_deploy.yml
--- a/.github/workflows/pypi_deploy.yml
+++ b/.github/workflows/pypi_deploy.yml
@@ -28,7 +28,7 @@ on:
         required: true
 
 jobs:
-  create-matrix:
+  preparations:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -39,28 +39,31 @@ jobs:
       - name: Install cibuildwheel
         run: pip install cibuildwheel
 
-      - name: Get package version number 
+      - name: Get package version number
         id: version-number
         run: |
           pip install scikit-build
           VERSION_NUMBER=$(python setup.py --version)
+          RAW_VERSION_NUMBER=$(cat ./VERSION) #x.y.z format even if z>=80
           echo "version_number=$VERSION_NUMBER" >> $GITHUB_OUTPUT
+          echo "raw_version_number=$RAW_VERSION_NUMBER" >> $GITHUB_OUTPUT
 
       - name: Verify tag version number
         if: ${{ github.event_name == 'push' }}
         run: |
-          TAG_VERSION_NUMBER=${TAG:1}
-          if [[ "$TAG_VERSION_NUMBER" != "$VERSION_NUMBER" ]]; then
-            echo "ERROR: The version number from the tag($TAG_VERSION_NUMBER) doesn't agree with the version number from from the package($VERSION_NUMBER)!"
+          TAG_VERSION_NUMBER=${TAG:1} #vx.y.z -> x.y.z
+          if [[ "$TAG_VERSION_NUMBER" != "$RAW_VERSION_NUMBER" ]]; then
+            echo "ERROR: The version number from the tag($TAG_VERSION_NUMBER) doesn't agree with the version number from from the package($RAW_VERSION_NUMBER)!"
             exit 1
           fi
         env:
-          VERSION_NUMBER: ${{ steps.version-number.outputs.version_number }}
+          RAW_VERSION_NUMBER: ${{ steps.version-number.outputs.raw_version_number }}
           TAG: ${{ github.ref_name }}
 
       - name: Generate setup matrix
         id: create-matrix
         run: |
+          sudo apt-get install -y jq
           MATRIX=$(python3 -c "import subprocess, json; \
           linux_identifiers = subprocess.check_output('cibuildwheel --print-build-identifiers --platform linux', shell=True).decode().splitlines(); \
           macos_identifiers = subprocess.check_output('cibuildwheel --print-build-identifiers --platform macos', shell=True).decode().splitlines(); \
@@ -70,9 +73,9 @@ jobs:
           echo "setup_matrix={\"include\":$MATRIX}" >> $GITHUB_OUTPUT
           echo "setup_nr=$(echo "$MATRIX" | jq length)" >> $GITHUB_OUTPUT
         env:
-          CIBW_ARCHS_MACOS: "x86_64 arm64"
-          CIBW_SKIP: pp* #TODO allow?
-          # CIBW_BUILD: cp39-* #TODO only for development
+          # CIBW_ARCHS_MACOS: "x86_64 arm64"
+          # CIBW_SKIP: pp*
+          CIBW_BUILD: cp39-* #TODO only for development
     outputs:
       setups: ${{ steps.create-matrix.outputs.setup_matrix }}
       setupNr: ${{ steps.create-matrix.outputs.setup_nr }}
@@ -80,11 +83,11 @@ jobs:
 
   build_wheels:
     name: Build ${{ matrix.identifier }} wheel
-    needs: create-matrix
+    needs: preparations
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
-      matrix: ${{ fromJson(needs.create-matrix.outputs.setups) }}
+      matrix: ${{ fromJson(needs.preparations.outputs.setups) }}
 
     steps:
       - uses: actions/checkout@v3
@@ -95,7 +98,7 @@ jobs:
       - uses: actions/setup-python@v4
         name: Install Python #Necessary for macos because default python version is too low for cibuildwheel
         with:
-          python-version: "3.10"
+          python-version: "3.11"
 
       - name: Build wheel
         uses: pypa/cibuildwheel@v2.12.3
@@ -112,7 +115,7 @@ jobs:
   build_sdist:
     name: Build source distribution
     runs-on: ubuntu-latest
-    needs: create-matrix
+    needs: preparations
     steps:
       - uses: actions/checkout@v3
         with:
@@ -128,13 +131,22 @@ jobs:
 
   upload_pypi:
     name: Upload to PyPI
-    needs: [create-matrix, build_wheels, build_sdist]
+    needs: [preparations, build_wheels, build_sdist]
     if: always() && inputs.DO_DEPLOY
     runs-on: ubuntu-latest
     environment:
       name: ${{ inputs.ENVIRONMENT }}
       url: ${{ vars.PYPI_URL }}
     steps:
+      - uses: actions/checkout@v3
+        with:
+          repository: ${{ inputs.REPOSITORY }}
+          ref: ${{ inputs.BRANCH }}
+          path: pkg_repo
+      - name: Verify being in a tag
+        run: git describe --exact-match --tags HEAD --match 'v*' ; echo $?
+        working-directory: pkg_repo
+
       - uses: actions/download-artifact@v3
         with:
           name: artifact
@@ -149,29 +161,19 @@ jobs:
       - name: Verify upload
         if: ${{ vars.PYPI_QUERY_URL != '' }}
         run: |
-          local_files=$(ls dist)
-          remote_files=$(curl -sX GET "${{ vars.PYPI_QUERY_URL }}/${{ needs.create-matrix.outputs.versionNr }}/json" | jq -r '.urls[] | select(.packagetype == "sdist" or .packagetype == "bdist_wheel") | .filename')
-
-          mapfile -t local_files_array <<< "$local_files"
-          mapfile -t remote_files_array <<< "$remote_files"
-
-          sorted_local_files=($(printf "%s\n" "${local_files_array[@]}" | sort))
-          sorted_remote_files=($(printf "%s\n" "${remote_files_array[@]}" | sort))
-
-          echo "Local Files:"
-          printf "%s\n" "${sorted_local_files[@]}"
-          echo "Remote Files:"
-          printf "%s\n" "${sorted_remote_files[@]}"
-
-          diff=$(comm -3 <(printf "%s\n" "${sorted_remote_files[@]}") <(printf "%s\n" "${sorted_local_files[@]}"))
-
-          if [ -z "$diff" ]; then
-            echo "The list of files is the same."
-          else
-            echo "The following files are different:"
-            printf "%s\n" "$diff"
-            exit 1
-          fi
+          python3 -c "import os,subprocess,json ;\
+          local_files = os.listdir('dist') ;\
+          local_files.sort() ;\
+          response_json = json.loads(subprocess.check_output(['curl', '-sX', 'GET', '${{ vars.PYPI_QUERY_URL }}/${{ needs.preparations.outputs.versionNr }}/json']).decode()) ;\
+          remote_files = [file_obj['filename'] for file_obj in response_json['urls'] if file_obj['packagetype'] in ['sdist', 'bdist_wheel']] ;\
+          remote_files.sort() ;\
+          print('Local Files:') ;\
+          print('\n'.join(local_files)) ;\
+          print('Remote Files:') ;\
+          print('\n'.join(remote_files)) ;\
+          diff = list(set(remote_files) - set(local_files)) ;\
+          print('The following files are different:\n','\n'.join(diff)) if diff else print('The list of files is the same.') ;\
+          exit(1) if diff else exit(0);"
 
       - name: Verify completeness
         run: |
@@ -183,5 +185,5 @@ jobs:
           fi
           echo "File count verified. Total files: $file_count"
         env:
-          expected_wheel_number: ${{needs.create-matrix.outputs.setupNr}}
+          expected_wheel_number: ${{needs.preparations.outputs.setupNr}}
 
