get version number from pkg, verify tag version nr

diff --git a/.github/workflows/pypi_deploy.yml b/.github/workflows/pypi_deploy.yml
--- a/.github/workflows/pypi_deploy.yml
+++ b/.github/workflows/pypi_deploy.yml
@@ -39,6 +39,25 @@ jobs:
       - name: Install cibuildwheel
         run: pip install cibuildwheel
 
+      - name: Get package version number 
+        id: version-number
+        run: |
+          pip install scikit-build
+          VERSION_NUMBER=$(python setup.py --version)
+          echo "version_number=$VERSION_NUMBER" >> $GITHUB_OUTPUT
+
+      - name: Verify tag version number
+        if: ${{ github.event_name == 'push' }}
+        run: |
+          TAG_VERSION_NUMBER=${TAG:1}
+          if [[ "$TAG_VERSION_NUMBER" != "$VERSION_NUMBER" ]]; then
+            echo "ERROR: The version number from the tag($TAG_VERSION_NUMBER) doesn't agree with the version number from from the package($VERSION_NUMBER)!"
+            exit 1
+          fi
+        env:
+          VERSION_NUMBER: ${{ steps.version-number.outputs.version_number }}
+          TAG: ${{ github.ref_name }}
+
       - name: Generate setup matrix
         id: create-matrix
         run: |
@@ -51,16 +70,17 @@ jobs:
           echo "setup_matrix={\"include\":$MATRIX}" >> $GITHUB_OUTPUT
           echo "setup_nr=$(echo "$MATRIX" | jq length)" >> $GITHUB_OUTPUT
         env:
-          CIBW_BUILD: cp39-* #TODO restriction for development
-          # CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
-          # CIBW_SKIP: pp* #TODO allow?
+          CIBW_ARCHS_MACOS: "x86_64 arm64"
+          CIBW_SKIP: pp* #TODO allow?
+          # CIBW_BUILD: cp39-* #TODO only for development
     outputs:
       setups: ${{ steps.create-matrix.outputs.setup_matrix }}
       setupNr: ${{ steps.create-matrix.outputs.setup_nr }}
+      versionNr: ${{ steps.version-number.outputs.version_number }}
 
   build_wheels:
-    needs: create-matrix
     name: Build ${{ matrix.identifier }} wheel
+    needs: create-matrix
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -92,6 +112,7 @@ jobs:
   build_sdist:
     name: Build source distribution
     runs-on: ubuntu-latest
+    needs: create-matrix
     steps:
       - uses: actions/checkout@v3
         with:
@@ -125,16 +146,11 @@ jobs:
           repository-url: ${{ vars.PYPI_UPLOAD_URL }}
           skip-existing: ${{ inputs.SKIP_EXISTING }}
 
-      - name: Get version number from tag
-        run: echo "VERSION_NUMBER=${tag:1}" >> $GITHUB_ENV
-        env:
-          tag: ${{ github.ref_name }}
-
       - name: Verify upload
         if: ${{ vars.PYPI_QUERY_URL != '' }}
         run: |
           local_files=$(ls dist)
-          remote_files=$(curl -sX GET "${{ vars.PYPI_QUERY_URL }}/${{env.VERSION_NUMBER}}/json" | jq -r '.urls[] | select(.packagetype == "sdist" or .packagetype == "bdist_wheel") | .filename')
+          remote_files=$(curl -sX GET "${{ vars.PYPI_QUERY_URL }}/${{ needs.create-matrix.outputs.versionNr }}/json" | jq -r '.urls[] | select(.packagetype == "sdist" or .packagetype == "bdist_wheel") | .filename')
 
           mapfile -t local_files_array <<< "$local_files"
           mapfile -t remote_files_array <<< "$remote_files"
