modify checking tag

diff --git a/.github/workflows/pypi_deploy.yml b/.github/workflows/pypi_deploy.yml
--- a/.github/workflows/pypi_deploy.yml
+++ b/.github/workflows/pypi_deploy.yml
@@ -7,10 +7,9 @@ on:
         type: string
         description: The repository to build from
         required: true
-      BRANCH:
+      REF:
         type: string
-        description: The repository branch to use
-        default: master
+        description: The repository tag/branch to use
         required: false
       DO_DEPLOY:
         type: boolean
@@ -34,10 +33,8 @@ jobs:
       - uses: actions/checkout@v3
         with:
           repository: ${{ inputs.REPOSITORY }}
-          ref: ${{ inputs.BRANCH }}
-
-      - name: Install cibuildwheel
-        run: pip install cibuildwheel
+          ref: ${{ inputs.REF }}
+          fetch-depth: 0
 
       - name: Get package version number
         id: version-number
@@ -48,17 +45,26 @@ jobs:
           echo "version_number=$VERSION_NUMBER" >> $GITHUB_OUTPUT
           echo "raw_version_number=$RAW_VERSION_NUMBER" >> $GITHUB_OUTPUT
 
+      - name: Check being on a tagged commit
+        id: check-for-tag
+        run: |
+          git describe --exact-match --tags HEAD --match 'v*' >/dev/null 2>&1 && ON_TAG=1 || ON_TAG=0
+          echo "on_tag=$ON_TAG" >> $GITHUB_OUTPUT
+    
       - name: Verify tag version number
-        if: ${{ github.event_name == 'push' }}
+        if: ${{ steps.check-for-tag.outputs.on_tag == '1' }}
         run: |
           TAG_VERSION_NUMBER=${TAG:1} #vx.y.z -> x.y.z
           if [[ "$TAG_VERSION_NUMBER" != "$RAW_VERSION_NUMBER" ]]; then
-            echo "ERROR: The version number from the tag($TAG_VERSION_NUMBER) doesn't agree with the version number from from the package($RAW_VERSION_NUMBER)!"
+            echo "ERROR: The version number from the tag($TAG_VERSION_NUMBER) doesn't agree with the version number from the package($RAW_VERSION_NUMBER)!"
             exit 1
           fi
         env:
           RAW_VERSION_NUMBER: ${{ steps.version-number.outputs.raw_version_number }}
           TAG: ${{ github.ref_name }}
+
+      - name: Install cibuildwheel
+        run: pip install cibuildwheel
 
       - name: Generate setup matrix
         id: create-matrix
@@ -75,11 +81,13 @@ jobs:
         env:
           # CIBW_ARCHS_MACOS: "x86_64 arm64"
           # CIBW_SKIP: pp*
-          CIBW_BUILD: cp39-* #TODO only for development
+          # CIBW_BUILD: cp39-* #TODO only for development
+          CIBW_BUILD: cp39-manylinux_x86_64 #TODO only for development
     outputs:
       setups: ${{ steps.create-matrix.outputs.setup_matrix }}
       setupNr: ${{ steps.create-matrix.outputs.setup_nr }}
       versionNr: ${{ steps.version-number.outputs.version_number }}
+      onTag: ${{ steps.check-for-tag.outputs.on_tag }}
 
   build_wheels:
     name: Build ${{ matrix.identifier }} wheel
@@ -93,7 +101,7 @@ jobs:
       - uses: actions/checkout@v3
         with:
           repository: ${{ inputs.REPOSITORY }}
-          ref: ${{ inputs.BRANCH }}
+          ref: ${{ inputs.REF }}
 
       - uses: actions/setup-python@v4
         name: Install Python #Necessary for macos because default python version is too low for cibuildwheel
@@ -120,7 +128,7 @@ jobs:
       - uses: actions/checkout@v3
         with:
           repository: ${{ inputs.REPOSITORY }}
-          ref: ${{ inputs.BRANCH }}
+          ref: ${{ inputs.REF }}
 
       - name: Build sdist
         run: pipx run build --sdist
@@ -132,20 +140,20 @@ jobs:
   upload_pypi:
     name: Upload to PyPI
     needs: [preparations, build_wheels, build_sdist]
-    if: always() && inputs.DO_DEPLOY
+    if: always() && needs.preparations.result == 'success' && inputs.DO_DEPLOY
     runs-on: ubuntu-latest
     environment:
       name: ${{ inputs.ENVIRONMENT }}
       url: ${{ vars.PYPI_URL }}
     steps:
-      - uses: actions/checkout@v3
-        with:
-          repository: ${{ inputs.REPOSITORY }}
-          ref: ${{ inputs.BRANCH }}
-          path: pkg_repo
-      - name: Verify being in a tag
-        run: git describe --exact-match --tags HEAD --match 'v*' ; echo $?
-        working-directory: pkg_repo
+      - name: Verify being on a tag
+        run: |
+          if [[ "${{ env.ON_TAG }}" != "1" ]]; then
+            echo "Error: Asked for deploying without a tag!"
+            exit 1
+          fi
+        env: 
+          ON_TAG: ${{ needs.preparations.outputs.onTag }}
 
       - uses: actions/download-artifact@v3
         with:
